version: '3'

services:
  web:
    build: .
    command: otree runprodserver1of2
    environment:
      - DATABASE_URL=postgres://postgres@db/postgres
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  worker:
    environment:
      - DATABASE_URL=postgres://postgres@db/postgres
      - REDIS_URL=redis://redis:6379
    build: .
    command: otree runprodserver2of2
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
  redis:
    image: redis
  db:
    image: postgres
